import streamlit as st

def generate_chat_response(user_input):
    """Generate AI response using Gemini with SEO context."""
    try:
        from src.gemini_client import safe_gemini_call
        import streamlit as st
        import pandas as pd

        # Build context from current session state
        context_parts = []

        if st.session_state.get("selected_keyword"):
            context_parts.append(f"Current analysis topic/seed keyword: {st.session_state.selected_keyword}")

        if st.session_state.get("keyword_results"):
            df = pd.DataFrame(st.session_state.keyword_results)
            if not df.empty and "keyword" in df.columns:
                top_keywords = df.nlargest(5, "score")["keyword"].tolist() if "score" in df.columns else df["keyword"].head(5).tolist()
                context_parts.append(f"Top analyzed keywords in session: {', '.join(top_keywords)}")

        if st.session_state.get("competitor_results"):
            comp = st.session_state.competitor_results
            if isinstance(comp, dict) and "opportunities" in comp:
                opps = [o.get("keyword", "") for o in comp.get("opportunities", []) if isinstance(o, dict)][:5]
                context_parts.append(f"Competitor gap opportunities: {', '.join(opps)}")

        if st.session_state.get("cluster_results"):
            clust = st.session_state.cluster_results
            if isinstance(clust, dict) and "clusters" in clust:
                names = [c.get("cluster_name", "") for c in clust.get("clusters", []) if isinstance(c, dict)][:5]
                context_parts.append(f"Semantic keyword clusters: {', '.join(names)}")

        if st.session_state.get("trend_results"):
            trend = st.session_state.trend_results
            if isinstance(trend, dict) and "insights" in trend:
                context_parts.append(f"Trend insights: {'; '.join(trend.get('insights', []))}")

        if st.session_state.get("serp_results"):
            serp = st.session_state.serp_results
            if isinstance(serp, dict) and "summary" in serp:
                context_parts.append(f"SERP Analysis summary: {serp.get('summary')}")

        if st.session_state.get("agent_strategy_report"):
            rep = st.session_state.agent_strategy_report
            if isinstance(rep, dict):
                context_parts.append(f"AI Strategy Report Executive Summary: {rep.get('executive_summary', '')}")
                recs = rep.get("recommendations", [])
                if recs:
                    context_parts.append("Strategy Recommendations:\n" + "\n".join(f"- {r}" for r in recs))

        context = "\n".join(context_parts) if context_parts else "No recent analysis data in the current session."

        prompt = f"""You are the Keylytics Research Assistant.

Your responsibility is to help users understand market intelligence findings, strategic recommendations, competitor insights, trend analysis, monitoring reports, and platform-generated outputs.

You do not replace the LangGraph workflow.
You do not function as a general-purpose chatbot.
Your role is to explain, summarize, contextualize, and help users interpret research generated by Keylytics.

Current session context:
{context}

User question: {user_input}

Provide a helpful, concise SEO-focused response explaining or summarizing the findings. Be specific and actionable.
If the user asks about starting a new keyword analysis, suggest they use the specific feature tabs or the Agent Mode.
Keep responses under 200 words."""

        response = safe_gemini_call(prompt, temperature=0.7)
        if response:
            return response
        return "I'm having trouble connecting to the AI model right now. Please try one of the analysis tabs above for detailed keyword research."
    except Exception as e:
        return f"I encountered an error: {str(e)}. Please use the analysis tabs above for your research needs."

def render_chat_interface():
    st.markdown("### 💬 Conversational SEO Assistant")
    # Initialize chat history
    if "messages" not in st.session_state:
        st.session_state.messages = []
    # Display chat messages
    chat_container = st.container()
    with chat_container:
        for message in st.session_state.messages:
            with st.chat_message(message["role"]):
                st.markdown(message["content"])
    # Chat input
    if prompt := st.chat_input("Ask me anything about SEO, keywords, or trends..."):
        # Add user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        # Add to search history
        if prompt not in st.session_state.search_history:
            st.session_state.search_history.append(prompt)
        # Display user message
        with st.chat_message("user"):
            st.markdown(prompt)
        # Generate assistant response
        with st.chat_message("assistant"):
            with st.spinner("Analyzing..."):
                response = generate_chat_response(prompt)
                st.markdown(response)
        # Add assistant message
        st.session_state.messages.append({"role": "assistant", "content": response})
