"""
Pydantic schema definitions for Keylytics.
These represent data contracts only (no business logic/agent execution)
used to structure validation, representation, and serialization of pipeline stages.
"""

from datetime import datetime
from enum import Enum
from typing import List, Dict, Any, Optional, Literal
from pydantic import BaseModel, Field, field_validator, ConfigDict
from src.data_quality import DataSource


class CompetitorEntry(BaseModel):
    """Represents a competitor's domain rank or metrics relative to a keyword."""
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    domain: str = Field(..., description="The competitor's domain name (e.g. example.com)")
    rank: int = Field(..., description="Organic search rank for the competitor")
    title: Optional[str] = Field(None, description="The page title shown in search results")
    url: Optional[str] = Field(None, description="The landing page URL")


class KeywordFinding(BaseModel):
    """Structured record of a single analyzed keyword suggestion."""
    model_config = ConfigDict(from_attributes=True, use_enum_values=True)

    seed: str = Field(..., description="The original seed keyword used for generation")
    keyword: str = Field(..., description="The suggested keyword variant")
    volume: float = Field(..., description="Search volume (monthly/annualized)")
    competition: Optional[float] = Field(None, description="Competition density index (0.0 to 1.0)")
    cpc: Optional[float] = Field(None, description="Cost-per-click value in USD")
    trend: Optional[float] = Field(None, description="Google Trends slope or relative value")
    score: float = Field(..., description="Calculated opportunity score")
    difficulty: Literal["Easy", "Medium", "Hard"] = Field(..., description="Difficulty classification level")
    intent: str = Field(..., description="Classified intent (e.g., Informational, Commercial)")
    competitors: List[CompetitorEntry] = Field(default_factory=list, description="Top organic competitor details")
    data_source: DataSource = Field(..., description="Origin source of core search metrics")
    trend_data_source: DataSource = Field(..., description="Origin source of trend metric")

    @field_validator("volume")
    @classmethod
    def validate_non_negative_volume(cls, v: float) -> float:
        if v < 0:
            raise ValueError("volume cannot be negative")
        return v

    @field_validator("score")
    @classmethod
    def validate_score_range(cls, v: float) -> float:
        if v < 0.0:
            raise ValueError("score must be non-negative")
        return v


class OpportunityScore(BaseModel):
    """Detailed breakdown of a keyword's calculated opportunity score."""
    model_config = ConfigDict(from_attributes=True)

    score: float = Field(..., description="Calculated opportunity score")
    difficulty: Literal["Easy", "Medium", "Hard"] = Field(..., description="Difficulty classification level")
    mode: Literal["standard", "lightweight"] = Field(..., description="Calculation mode used")
    volume: float = Field(..., description="Input search volume")
    cpc: Optional[float] = Field(None, description="Input cost-per-click")
    competition: Optional[float] = Field(None, description="Input competition index")

    @field_validator("score")
    @classmethod
    def validate_score_range(cls, v: float) -> float:
        if v < 0.0:
            raise ValueError("score must be non-negative")
        return v


class IntelligenceFindings(BaseModel):
    """Aggregate search intelligence results for a seed keyword."""
    model_config = ConfigDict(from_attributes=True)

    seed_keyword: str = Field(..., description="Seed keyword utilized for search")
    keyword_findings: List[KeywordFinding] = Field(..., description="List of generated keywords and metrics")
    competitor_gap: Optional[Dict[str, Any]] = Field(None, description="Aggregated competitor gap analysis raw data")
    topic_clusters: Optional[Dict[str, Any]] = Field(None, description="Aggregated topic cluster analysis raw data")
    trend_forecast: Optional[Dict[str, Any]] = Field(None, description="Aggregated trends forecasting raw data")
    serp_analysis: Optional[Dict[str, Any]] = Field(None, description="Aggregated SERP analysis raw data")
    generated_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when findings were generated")


class StrategyReport(BaseModel):
    """Top-level strategic marketing deliverable based on intelligence findings."""
    model_config = ConfigDict(from_attributes=True)

    seed_keyword: str = Field(..., description="Original seed keyword analyzed")
    executive_summary: str = Field(..., description="High-level markdown summary generated by AI agent")
    findings: IntelligenceFindings = Field(..., description="Underlying search intelligence findings data container")
    top_opportunities: List[KeywordFinding] = Field(..., description="Curated high-scoring keyword opportunities")
    recommendations: List[str] = Field(..., description="List of actionable strategic recommendations")
    generated_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of report generation")
    version: str = Field("phase2a", description="Schema/platform version")


class ResearchPlan(BaseModel):
    """Strategic objectives and boundary configurations for a keyword research task."""
    model_config = ConfigDict(from_attributes=True)

    seed_keyword: str = Field(..., description="Seed keyword to analyze")
    objectives: List[str] = Field(..., description="Specific goal objectives for the research")
    requested_modules: List[Literal["keyword_discovery", "competitor_gap", "topic_clustering", "trend_forecasting", "serp_analysis"]] = Field(
        ..., description="List of components/modules requested for analysis"
    )
    max_keywords: int = Field(..., description="Maximum limit of keyword suggestions to generate")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of plan creation")

    @field_validator("max_keywords")
    @classmethod
    def validate_max_keywords_range(cls, v: int) -> int:
        if not (1 <= v <= 50):
            raise ValueError("max_keywords must be between 1 and 50")
        return v


class MarketState(BaseModel):
    """
    Foundation state model representing the shared context threaded between nodes.
    This is currently a model container only and does not contain graph execution behavior.
    """
    model_config = ConfigDict(from_attributes=True)

    research_plan: ResearchPlan = Field(..., description="The configured plan triggering state")
    findings: Optional[IntelligenceFindings] = Field(None, description="Aggregated keyword discovery outputs")
    report: Optional[StrategyReport] = Field(None, description="Constructed high-level marketing strategy report")
    status: Literal["pending", "in_progress", "completed", "failed"] = Field("pending", description="Overall state progress status")
    errors: List[str] = Field(default_factory=list, description="Collection of execution error details")
